#!/bin/bash

setup_motd()
{
    echo >> /etc/motd
    echo 'You can configure this system or install to disk using "sudo k3os install"' >> /etc/motd
}

setup_base()
{
    K3OS_ISO=$(blkid -L K3OS || true)
    if [ -n "$K3OS_ISO" ]; then
        mount -o ro $(blkid -L K3OS) /.base
    fi
}

setup_passwd()
{
    # no passwords in live mode
    passwd -d rancher >/dev/null 2>&1
}

setup_base
setup_kernel
setup_passwd
setup_motd
